---
abstract: 'Catalyst FormBuilder Base Controller'
author:
  - 'Copyright (c) 2006 Juan Camacho <formbuilder@suspenda.com>. All Rights Reserved.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-FormBuilder
no_index:
  directory:
    - inc
    - t
recommends:
  Catalyst::View::TT: 0.23
requires:
  CGI::FormBuilder: 3.02
  Catalyst::Runtime: 5.7
  Class::Data::Inheritable: 0.04
  Class::Inspector: 1.13
  MRO::Compat: 0.09
  Scalar::Util: 1.19
  Test::WWW::Mechanize::Catalyst: 0.37
  Tie::IxHash: 1.21
version: 0.05
